/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CS2CppAPI {
  public static int fact(int n) {
    int ret = CS2CppAPIPINVOKE.fact(n);
    return ret;
  }

}
